apiVersion: v1
kind: ConfigMap
metadata:
  name: gaia-abiz-config
  namespace: gaia-abiz
data:
  APP_NAME: "GaiA-ABiz-Backend"
  APP_VERSION: "1.0.0"
  DEBUG: "False"
  HOST: "0.0.0.0"
  PORT: "8000"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "10"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  KEY_ROTATION_DAYS: "90"
  OPENAI_MODEL: "gpt-4"
  LLM_TEMPERATURE: "0.7"
  LLM_MAX_TOKENS: "2000"
  MILVUS_COLLECTION_NAME: "gaia_embeddings"
  PROMETHEUS_PORT: "9090"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  KUBERNETES_NAMESPACE: "gaia-abiz"
