apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-abiz-backend
  namespace: gaia-abiz
  labels:
    app: gaia-abiz-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gaia-abiz-backend
  template:
    metadata:
      labels:
        app: gaia-abiz-backend
    spec:
      containers:
      - name: api
        image: gaia-abiz-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: gaia-abiz-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gaia-abiz-secrets
              key: secret-key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: gaia-abiz-secrets
              key: encryption-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gaia-abiz-secrets
              key: openai-api-key
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: gaia-abiz-secrets
              key: oauth2-client-id
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gaia-abiz-secrets
              key: oauth2-client-secret
        - name: MILVUS_HOST
          value: "milvus-service"
        - name: MILVUS_PORT
          value: "19530"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gaia-abiz-backend-service
  namespace: gaia-abiz
spec:
  selector:
    app: gaia-abiz-backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer
